<!-- Day 3 Mini Project: NUMPY -->

<h3 style="color:#c06d15; font-weight:bold;">Day 3 Mini Project: <span style="color:#43a047;">NUMPY</span></h3>

<h4 style="color:#d84315; font-weight:bold;">
    📝 Done by: <span style="color:#6a1b9a;">Ishat Noor Mahi</span>
</h4>
<p style="color:#00838f; font-weight:bold; font-size:1.1em;">
    <b>Statistics 1/1</b><br>
    <b>ID:</b> <code style="color:#c62828;">Mahi-3006</code>
</p>

<p>
    📄 <a href="https://docs.google.com/document/d/1Aan31bwy9JynXsOPraWIzrOPl09w_nak68c5ex8MHks/edit?tab=t.0" style="color:#1565c0; font-weight:bold;">Project Documentation Link</a>
</p>

<hr>

<blockquote style="border-left:4px solid #43a047; padding-left:10px; color:#333;">
    Assigned: 23/08/2025
</blockquote>


In [ ]:
import numpy as np

In [17]:
# 1) Creating 2 arrays with 5 elements, contaiing numbers between 0 to 100 
arr1 = np.random.uniform(0,100,5).astype(float)
arr2 = np.random.uniform(0,100,5).astype(float)
print(arr1)
print(arr2)

[27.59230828  9.69743447 37.38824933 56.08310912 56.48946811]
[92.01798394 43.08247843 76.03157853 48.72806418 93.65518883]


In [31]:
# 2)
# i.Perform  Basic Caluclations
print("Sum: ",arr1.sum())
print("Mean: ",arr1.mean())
print("Maximum: ",arr1.max())
print("Minimum: ",arr1.min())
print("Standard deviation: ",arr1.std())

Sum:  187.25056932178794
Mean:  37.45011386435759
Maximum:  56.4894681081032
Minimum:  9.697434474262067
Standard deviation:  17.759937464746


In [25]:
# ii.Explore array properties:
print("shape: ",arr1.shape)
print("shape: ",arr1.shape)
print("shape: ",arr1.shape)
print("Data Type: ",arr1.dtype)

shape:  (5,)
shape:  (5,)
shape:  (5,)
Data Type:  float64


In [50]:
# iii.Reshape the array and display it.
new_arr1 = arr1.reshape(5,1)
print(new_arr1)

[[27.59230828]
 [ 9.69743447]
 [37.38824933]
 [56.08310912]
 [56.48946811]]


In [37]:
# iv. Indexing & Slicing
print(new_arr1[1])

print(new_arr1[2:4])

[9.69743447]
[[37.38824933]
 [56.08310912]]


In [49]:
# 3) Perform 2 basic arithmetic operations between the first and second array

print("Addition:", arr1 + arr2)
print("Subtraction:", arr1- arr2)

Addition: [119.61029223  52.7799129  113.41982786 104.81117331 150.14465693]
Subtraction: [-64.42567566 -33.38504396 -38.6433292    7.35504494 -37.16572072]
