## Dictionary

In [10]:
def funct2(x):
    return x*x
dict1 = {
    "name":"mahi",
    "func_key": lambda x: x*x
}


In [3]:
print(dict1)

{'name': 'mahi'}


In [4]:
dict1["name"] = "ishat"
print(dict1)

{'name': 'ishat'}


In [8]:
dict1.get("func_key")(5)

25

In [11]:
type(dict1.keys())

dict_keys

# NUMPY

In [12]:
!pip install numpy

In [20]:
import numpy as np

In [22]:
arr = np.array([2,4,6])
print(arr)
type(arr)

[2 4 6]


numpy.ndarray

### print dimention


In [23]:
arr.ndim

1

In [24]:
arr2 = np.array([[[2,3,4]]])
print(arr2)
print(arr2.ndim)

[[[2 3 4]]]
3


In [26]:
arr3 = np.array([[2,3,4],[1,2,3]])
print(arr3)
print(arr3.ndim)

[[2 3 4]
 [1 2 3]]
2


**list length have to same**

### Multi dimention

In [29]:
arr4 = np.array([[[2,5,6],[1,2,3]],[[11,23,4],[43,3,55]]])
print(arr4.ndim)

3


In [30]:
print(arr4)

[[[ 2  5  6]
  [ 1  2  3]]

 [[11 23  4]
  [43  3 55]]]


**3D shape === (block, num of rows in each block, num of cols in each block)**

In [32]:
arr4.shape

(2, 2, 3)

***different data type allowed but will be converted to string***

In [36]:
mix_arr = np.array([1,3,True,"mahi"])
print("type",mix_arr.dtype)
print(mix_arr) #all strings

type <U21
['1' '3' 'True' 'mahi']


### zeros, ones

# indexing and slicing

In [42]:
arr6 = np.array([[2,4,5],[1,2,3],[4,5,6],[3,4,1]])

In [43]:
arr6

array([[2, 4, 5],
       [1, 2, 3],
       [4, 5, 6],
       [3, 4, 1]])

In [41]:
arr6.ndim

2

## [rows range,col range]
### index from 0, exclusive ending

In [46]:
arr6[0:2,0:2] 

array([[2, 4],
       [1, 2]])

In [50]:
arr7 = np.array([[[3,5,7],[6,8,10]]])
#print 8
print(arr7)
arr7[0,0,1:3]

[[[ 3  5  7]
  [ 6  8 10]]]


array([5, 7])

In [51]:
arr8 = np.array([
    [ [1, 2, 3],
      [4, 5, 6] ],

    [ [7, 8, 9],
      [10, 11, 12] ]
])

## Matrix Calculations

20,28,29,30